title: Chinazom Chukwuemeka # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data analyst with 5+ years of combined expertise in data analytics and project management within the technology, 
  health, and municipality domains. Passionate about working with executive interdisciplinary teams and delivering 
  data-driven insights that improved business processes by over 35% and generated a revenue of over $1.1M.
  <br><br>
  Educational Qualifications: 
  <br><br>
  Masters of Science in Business Analytics, University of Lethbridge, Canada 2023 <br>
  Masters of Science, Informatics (Health), Indiana University Bloomington, USA 2019 <br>
  Bachelor of Science, Computer Information Systems, Babcock University, Nigeria 2014
  <br><br>
  <a href="https://www.linkedin.com/in/chinazomchukwuemeka/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
