title: Chinazom Chukwuemeka # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data analyst with 5+ years of combined expertise in data analytics and business analysis within the technology, 
  <br>health, and municipality domains. Passionate about working with executive interdisciplinary teams and delivering 
  <br> data-driven insights that improved business process by over 35% and generated a revenue of over $1.1M.
  <br><br>
  Educational Qualifications: Masters of Science in Business Analytics from the University of Lethbridge, Canada <br> 
  Bachelor's degree in Computer Information Systems
  <br><br>
  <a href="https://www.linkedin.com/in/chinazomchukwuemeka/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
