title: Chinazom Chukwuemeka # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data analyst and certified scrum master with 5+ years of combined expertise in data analytics and project management 
  within the technology, health, and municipality domains. Possess a master's degree in health informatics from Indiana University, USA 
  and another in business analytics from the University of Lethbridge, Canada.
  <br><br>
  Currently working with the futures and resilience team at the City of Calgary as a data analyst working to identify signals and disruptions
  of the future to help inform resilience efforts within Calgary.
  <br><br>
  <a href="https://www.linkedin.com/in/chinazomchukwuemeka/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
